spring:
  profiles:
    active: ${SPRING_PROFILE}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}
    driver-class-name: org.postgresql.Driver
